# 2. Tipovi podataka




## 2.4. Tekstualni tip podataka: string

String je kolekcijski nepromjenjivi uređeni tekstualni tip podataka:
* kolekcijski - jer predstavlja kolekciju znakova
* nepromjenjivi - jer znakovi u kolekcij se ne mogu mijenjati
* uređeni - jer znakovima se pristupa preko indeksa
* tekstualni - jer elementi kolekcije su znakovi

---

#### Definiranje

String je **tekstualni tip podataka** u Pythonu, namijenjen za pohranu i obradu teksta.  
String se zapisuje unutar jednostrukih (`'...'`) ili dvostrukih (`"..."`) navodnika. Python ne pravi razliku između njih – oba načina su jednako ispravna.

Osim toga, za tekst koji zauzima više redaka koriste se trostruki navodnici (`'''...'''` ili `"""..."""`).  
Stringovi u Pythonu su **nepromjenjivi (immutable)** – jednom kreirani ne mogu se mijenjati, nego se pri izmjeni stvara novi string.

**Primjeri:**

* `'Python'` i `"Python"` su isti tip podatka
* `"""Ovo je višelinijski string"""`
* `''` i `""` predstavlja prazan string

✏️ **Zadatak:**

1. Definiraj string u jednostrukim navodnicima i ispiši ga.
2. Definiraj string u dvostrukim navodnicima i ispiši ga.
3. Definiraj višelinijski string pomoću trostrukih navodnika i ispiši ga.
4. Definiraj prazan string i ispiši ga.

In [1]:
# String u jednostrukim navodnicima
a = 'Ovo je string'
print(a)

# String u dvostrukim navodnicima
b = "I ovo je string"
print(b)

# Višelinijski string
c = """Ovo je
string koji se
proteže kroz više redaka."""
print(c)

# Prazan string
d = ""
print("Prazan string:", d)

Ovo je string
I ovo je string
Ovo je
string koji se
proteže kroz više redaka.
Prazan string: 



---

#### Posebni znakovi

U Pythonu možemo koristiti **posebne znakove (escape znakove)** za prikazivanje znakova koje je teško ili nemoguće napisati izravno u stringu.
Za to se koristi znak **obrnute kose crte** (`\`).

Najčešći posebni znakovi su:

| Posebni znak | Značenje                                    | Primjer koda                          | Rezultat ispisa                       |
| ------------ | ------------------------------------------- | ------------------------------------- | ------------------------------------- |
| `\n`         | novi red                                    | `"Ovo je prvi red\nOvo je drugi red"` | `Ovo je prvi redOvo je drugi red` |
| `\t`         | tabulator (vodoravni razmak)                | `"Ime:\tAna"`                         | `Ime:    Ana`                         |
| `\\`         | obrnuta kosa crta                           | `"C:\\Programi\\Python"`              | `C:\Programi\Python`                  |
| `\"`         | dvostruki navodnik unutar stringa           | `"On je rekao: \"Python je super!\""` | `On je rekao: "Python je super!"`     |
| `\'`         | jednostruki navodnik unutar stringa         | `'It\'s Python'`                      | `It's Python`                         |


Posebnim znakovima se omogućuje stavljanje znakova u string koje inače ne bismo mogli napisati izravno.

✏️ **Zadatak:**

1. Definiraj string koji ispisuje dva retka teksta pomoću znaka za novi red (`\n`).
2. Definiraj string koji sadrži tabulator (`\t`).
3. Definiraj string pomoću dvostrukih navodnika koji u sebi sadrži dvostruke navodnike.
4. Definiraj string koji prikazuje putanju `C:\Programi\Python`.

In [2]:
# Novi red
s1 = "Ovo je prvi red\nOvo je drugi red"
print(s1)

# Tabulator
s2 = "Ime:\tAna"
print(s2)

# Navodnici unutar stringa
s3 = "On je rekao: \"Python je super!\""
print(s3)

# Obrnuta kosa crta u putanji
s4 = "C:\\Programi\\Python"
print(s4)


Ovo je prvi red
Ovo je drugi red
Ime:	Ana
On je rekao: "Python je super!"
C:\Programi\Python



---

#### Indeksiranje

Svaki znak u stringu u Pythonu ima svoj **indeks**, počevši od 0 za prvi znak. Indeksiranje nam omogućuje da dohvatimo ili provjerimo pojedinačne znakove unutar stringa.

* **Pozitivni indeksi**: Broje znakove od početka stringa (prvi znak je indeks 0, drugi 1, itd.).
* **Negativni indeksi**: Broje znakove od kraja stringa (posljednji znak je indeks -1, pretposljednji -2, itd.).

**Primjeri:**

| Znak             | P  | y  | t  | h  | o  | n  |
| ---------------- | -- | -- | -- | -- | -- | -- |
| Pozitivni indeks | 0  | 1  | 2  | 3  | 4  | 5  |
| Negativni indeks | -6 | -5 | -4 | -3 | -2 | -1 |

* `s = "Python"`
* `s[0]` → `'P'`  # prvi znak
* `s[3]` → `'h'`  # četvrti znak
* `s[-1]` → `'n'`  # posljednji znak
* `s[-2]` → `'o'`  # pretposljednji znak

>  **Napomena**  
> string je nepromjenjivi tip podatka, To znači da ne možemo mijenjati znakove na određenom indeks
> na primjer, ako je `s = "Python"` onda će `s[0] = "C"` javiti pogrešku.

✏️ **Zadatak:**

1. Definiraj varijablu `rijec` i dodijeli joj neku riječ.
2. Ispiši prvi znak riječi koristeći pozitivni indeks.
3. Ispiši posljednji znak riječi koristeći negativni indeks.
4. Ispiši treći znak riječi koristeći pozitivni indeks.
5. Ispiši pretposljednji znak riječi koristeći negativni indeks.


In [3]:
rijec = "jabuka"

print(rijec[0])
print(rijec[-1])
print(rijec[2])
print(rijec[-2])

j
a
b
k



---

#### Rezanje (slicing)

Python omogućuje dohvat dijelova stringa pomoću **rezanja** (slicing). Rezanje nam daje podstring bez mijenjanja izvornog stringa. Sintaksa je:

```
s[start:stop:step]
```

* **start** – indeks prvog znaka koji želimo uključiti
* **stop** – indeks znaka **iza** posljednjeg znaka kojeg želimo uključiti
* **step** – korak kojim prolazimo kroz string (po defaultu 1)

Ako izostavimo `start`, rezanje počinje od početka stringa.
Ako izostavimo `stop`, rezanje ide do kraja stringa.
Ako izostavimo `step`, koristi se korak 1.

**Primjeri:**

```python
s = "Python"
s[0:4]     # 'Pyth' – znakovi od indeksa 0 do 3
s[2:]      # 'thon' – od indeksa 2 do kraja
s[:3]      # 'Pyt' – od početka do indeksa 2
s[::2]     # 'Pto' – svaki drugi znak
s[::-1]    # 'nohtyP' – string u obrnutom redoslijedu
```

>  **Napomena**  
> string je nepromjenjivi tip podatka, stoga se ne može promijeniti znak na određenom indeksu  
> Na primjer, ako je `s = "Python"` onda će `s[0] = "C"` javiti pogrešku.  
> Ako želimo promijeniti znak, moramo stvoriti novi string koristeći rezanje i spajanje.  
> Na primjer,  `s = "C" + s[1:]`

✏️ **Zadatak:**

1. Definiraj varijablu `rijec` i dodijeli joj riječ duljine najmanje 6 znakova, npr. `"Python"`.
2. Ispiši prvi i zadnji znak riječi koristeći **indeksiranje**.
3. Ispiši srednji dio riječi (bez prvog i zadnjeg znaka) koristeći **slicing**.
4. Kreiraj novi string koji sadrži:
   * prvi znak
   * zadnji znak
   * srednji dio riječi u obrnutom redoslijedu
   * spojeno u jednu novu riječ koristeći **operator `+`**
5. Ispiši novi string.

In [4]:
rijec = "Python"
print(rijec[0], rijec[-1])
print(rijec[1:-1])
nova_rijec = rijec[0] + rijec[-1] + rijec[-1:1:-1]
print(nova_rijec)


P n
ytho
Pnnoht



---

#### Operatori spajanja i ponavljanja

U Pythonu stringovi podržavaju neke osnovne operacije pomoću **operatora**, što omogućuje jednostavnu manipulaciju tekstom. Najčešće korišteni operatori za stringove su **+** i **\***.

* **Spajanje stringova (`+`)**: Operator `+` spaja dva ili više stringova u jedan novi string. Ovo je poznato i kao **concatenation**.
* **Ponavljanje stringova (`*`)**: Operator `*` ponavlja string određeni broj puta, što je korisno kada želimo duplicirati tekst.

**Primjeri:**

* `"Hello, " + "world!"` → `'Hello, world!'`
* `"ha" * 4` → `'hahaha'`
* `("Python " * 2) + "rocks"` → `'Python Python rocks'`

✏️ **Zadatak:**

1. Definiraj varijablu `pozdrav` i dodijeli joj tekst `"Bok"`,
2. Definiraj varijablu `ime` i dodijeli joj svoje ime.
3. Spoji `pozdrav` i `ime` pomoću operatora `+` i ispiši rezultat. (ne zaboravi staviti razmak)
4. Ponavljaj svoj nadimak ili inicijale 3 puta koristeći operator `*` i ispiši rezultat.
5. Kreiraj kombinaciju spajanja i ponavljanja, npr. Pozdrav `"Hej!"` ponovi 2 puta i nakon toga spoji s imenom


In [5]:
pozdrav = "Bok"
ime = "Branko"
print(pozdrav + " " + ime)

print("BŽ" * 3)  # Output: BŽBŽBŽ

print("Hej! " * 2 + ime)  # Output: Hej! Hej! Branko


Bok Branko
BŽBŽBŽ
Hej! Hej! Branko



---

#### Operatori pripadnosti

Python omogućuje jednostavnu provjeru **pripadnosti podstringa nekom stringu** pomoću operatora `in`. Ovaj operator vraća **`True` ili `False`** ovisno o tome postoji li traženi znak ili podstring u tekstu.

> **Napomena:** Python je **osjetljiv na velika i mala slova**, pa `"py" in "Python"` vraća `False`.

**Primjeri:**

```python
s = "Python"

print("y" in s)    # True, 'y' postoji u stringu
print("z" in s)    # False, 'z' ne postoji
print("Py" in s)   # True, podstring 'Py' postoji
print("py" in s)   # False, mala slova ne odgovaraju
print("z" not in s)  # True, 'z' nije prisutan
```


✏️ **Zadatak:**

1. Definiraj varijablu `rijec` i dodijeli joj string `"Programiranje"`.
2. Provjeri je li slovo `"g"` u `rijec` i ispiši rezultat.
3. Provjeri je li slovo `"R"` **nije** u `rijec` pomoću `not in`.
4. Provjeri je li podstring `"gram"` u `rijec`.
5. Provjeri je li podstring `"Gram"` u `rijec`.

In [18]:
rijec = "Programiranje"
print("g" in rijec)
print("R" not in rijec)
print("gram" in rijec)
print("Gram" in rijec)

True
True
True
False



---

#### Ugrađene funkcije za stringove

Osim metoda koje su dio samog tipa `str`, Python nudi i **ugrađene funkcije** koje možemo primijeniti na stringove. One omogućuju provjeru duljine, pretvorbu znakova, pronalaženje minimalnih i maksimalnih vrijednosti i druge operacije.

| Funkcija     | Opis                                                                                        | Primjer                                     |
| ------------ | ------------------------------------------------------------------------------------------- | ------------------------------------------- |
| `len(s)`     | vraća duljinu stringa (broj znakova)                                                        | `len("Python")` → `6`                       |
| `str(obj)`   | pretvara objekt u string                                                                    | `str(123)` → `"123"`                        |
| `repr(obj)`  | vraća službeni (programerski) prikaz stringa                                                | `repr("Ana\n")` → `'Ana\n'`                 |
| `chr(i)`     | vraća znak za Unicode kodni broj `i`                                                        | `chr(65)` → `'A'`                           |
| `ord(c)`     | vraća Unicode kodni broj znaka `c`                                                          | `ord('A')` → `65`                           |
| `max(s)`     | vraća znak s najvećom Unicode vrijednošću                                                   | `max("abc")` → `'c'`                        |
| `min(s)`     | vraća znak s najmanjom Unicode vrijednošću                                                  | `min("abc")` → `'a'`                        |
| `all(s)`     | vraća `True` ako su svi znakovi u stringu "istinito evaluirani" (npr. nema praznih znakova) | `all("abc")` → `True`                       |
| `any(s)`     | vraća `True` ako postoji barem jedan "istinito evaluiran" znak                              | `any("  ")` → `False`, `any("a ")` → `True` |



> **Napomena**
>
> * Ove funkcije su **opće ugrađene funkcije Pythona**, ali se mogu koristiti i sa stringovima.  
> * Neke od njih (`all`, `any`, `max`, `min`) rade s bilo kojim ***iterabilnim objektom**, a string se u Pythonu ponaša kao niz znakova, pa su i za njega primjenjive.



✏️ **Zadatak:**

1. Definiraj string `s = "Python"`.
2. Ispiši duljinu string`s`. 
3. Pretvori znak `'A'` u broj i broj `90` u znak.
4. Probaj funkcije `all()` i `any()` na stringovima `"abc"`, `""` i `"   "` (praznine).

In [9]:
s = "Python"
print("Duljina od",repr(s),"je", len(s))            

# najveći i najmanji znak po Unicode vrijednosti
print("Najveći znak po Unicode vrijednosti:", max(s))
print("Najmanji znako po Unicode vrijednosti:", min(s))

# pretvorbe pomoću ord i chr
print("Unocode vrijednost od A:", ord('A'))
print("Znak za Unicode vrijednost od 90 je:", chr(90))

# all i any primjeri
s = "abc"
print("all od", repr(s), all(s))
print("any od", repr(s), any(s))

s = "   "
print("all od", repr(s), all(s))
print("any od", repr(s), any(s))

s = ""
print("all od", repr(s), all(s))
print("any od", repr(s), any(s))


Duljina od 'Python' je 6
Najveći znak po Unicode vrijednosti: y
Najmanji znako po Unicode vrijednosti: P
Unocode vrijednost od A: 65
Znak za Unicode vrijednost od 90 je: Z
all od 'abc' True
any od 'abc' True
all od '   ' True
any od '   ' True
all od '' True
any od '' False



---

#### Metode za promjenu oblika stringa

Metoda je **funkcija koja je vezana uz objekt**. Kada se metoda poziva na stringu, ona može vratiti novi string ili neku vrijednost, a originalni string ostaje nepromijenjen (osim ako eksplicitno ne dodijelimo rezultat nazad u varijablu). Sintaksa je:

```python
objekt.metoda(argumenti)
```

Python nudi metode koje omogućuju **promjenu izgleda teksta** bez mijenjanja izvornog stringa. Ove metode vraćaju **novi string** i često se koriste za čišćenje ili formatiranje teksta.

**Najčešće korištene metode:**

| Metoda          | Opis                                | Primjer                         | Rezultat               |
| --------------- | ----------------------------------- | ------------------------------- | ---------------------- |
| `.upper()`      | Pretvara sve znakove u velika slova | `"Python".upper()`              | `'PYTHON'`             |
| `.lower()`      | Pretvara sve znakove u mala slova   | `"Python".lower()`              | `'python'`             |
| `.capitalize()` | Prvo slovo veliko, ostalo malo      | `"python PROGRAM".capitalize()` | `'Python program'`     |
| `.title()`      | Prvo slovo svake riječi veliko      | `"python program".title()`      | `'Python Program'`     |
| `.swapcase()`   | Velika slova postaju mala i obrnuto | `"PyThOn".swapcase()`           | `'pYtHoN'`             |
| `.strip()`      | Uklanja vodeće i završne praznine   | `"  Python  ".strip()`          | `'Python'`             |
| `.lstrip()`     | Uklanja praznine s lijeve strane    | `"  Python".lstrip()`           | `'Python'`             |
| `.rstrip()`     | Uklanja praznine s desne strane     | `"Python  ".rstrip()`           | `'Python'`             |

>  **Napomena**
>
> Prazni znakovi (whitespace) uključuju razmake, tabove `\t` i znakove novog reda `\n`. Metode `.strip()`, `.lstrip()` i `.rstrip()` uklanjaju upravo ove prazne znakove s početka i kraja stringa.
> Metode `.strip()`, `.lstrip()` i `.rstrip()` imaju argument s zadanom vrijednošću `chars=None`. Ako se ne postavi, uklanja prazne znakove. U suprotnom, uklanja samo navedene znakove.  
> Na primjer, `"banana".strip("an")` vraća `"b"`.

✏️ **Zadatak:**

1. Definiraj varijablu `tekst` i dodijeli joj rečenicu s najmanje 10 znakova, s prazninama i mješovitim slovima, npr. `"  PyThOn je Zakon!  "`.
2. Ukloni vodeće i završne praznine koristeći `.strip()`.
3. Dohvati prvi i zadnji znak teksta koristeći **indeksiranje**.
4. Izdvoji srednji dio teksta (bez prvog i zadnjeg znaka) koristeći **slicing**.
5. Pretvori srednji dio u **mala slova** koristeći `.lower()`.
6. Spoji prvi znak, srednji dio i zadnji znak u **novi string** `novi` koristeći operator `+` i ispiši ga.
7. Pretvori novi string u **velika slova** koristeći `.upper()` i ispiši ga.

In [10]:
tekst = "  PyThOn je Zakon!  "

tekst = tekst.strip()

prvi = tekst[0]
zadnji = tekst[-1]

srednji = tekst[1:-1]

srednji = srednji.lower()

novi = prvi + srednji + zadnji
print(novi)

print(novi.upper())

Python je zakon!
PYTHON JE ZAKON!



---

#### Metode za pretragu i provjeru sadržaja stringa

Python nudi metode koje omogućuju **traženje podstringova** i **provjeru sadržaja** stringa. Ove metode su korisne kada želimo provjeriti prisutnost određenih znakova ili dijelova teksta, broj pojavljivanja ili tip znakova u stringu.

**Najčešće korištene metode:**

| Metoda             | Opis                                                             | Primjer                     | Rezultat |
| ------------------ | ---------------------------------------------------------------- | --------------------------- | -------- |
| `.find(sub, start=0)`       | Prvi indeks pojavljivanja podstringa; vraća -1 ako ne postoji. Podstring se traži od indeksa `start`.    | `"Python".find("th")`       | `2`      |
| `.index(sub, start=0)`      | Prvi indeks pojavljivanja podstringa; baca grešku ako ne postoji. Podstring se traži od indeksa `start`. | `"Python".index("th")`      | `2`      |
| `.count(sub)`      | Broj pojavljivanja podstringa                                    | `"banana".count("na")`      | `2`      |
| `.startswith(sub)` | Provjerava počinje li string s podstringom                       | `"Python".startswith("Py")` | `True`   |
| `.endswith(sub)`   | Provjerava završava li string s podstringom                      | `"Python".endswith("on")`   | `True`   |
| `.isalpha()`       | Provjerava jesu li svi znakovi slova                             | `"Python".isalpha()`        | `True`   |
| `.isdigit()`       | Provjerava jesu li svi znakovi brojevi                           | `"123".isdigit()`           | `True`   |
| `.isalnum()`       | Provjerava jesu li svi znakovi slova ili brojevi                 | `"Python3".isalnum()`       | `True`   |
| `.isspace()`       | Provjerava jesu li svi znakovi praznine                          | `"   ".isspace()`           | `True`   |

✏️ **Zadatak:**

1. Definiraj varijablu `tekst` i dodijeli joj rečenicu s najmanje 15 znakova, s prazninama i mješovitim slovima, npr. `"  PyThOn 123 rastura!  "`.
2. Ukloni vodeće i završne praznine koristeći `.strip()`.
4. Pronađi indekse prvog i drugog pojavljivanja praznog znaka `" "` i spremi ih u varijable `i1` i `i2`
5. Temeljem varijabli `i1` i `i2` odreži podstringove `PyThOn`, `123` i `rastura!` koje sačuvaj u varijablama `s1`, `s2` i `s3` te ih ispiši.
6. Provjeri je li podstring u `s1` alfanumerički.
7. Provjeri je li podstring u `s2` brojčani.
8. Provjeri je li podstring u `s3` alfanumerički.
10. Provjeri počinje li podstring u `s1` s `"PyT"` i završava s `"On"` pomoću `.startswith()` i `.endswith()`.
11. Ispiši broj pojavljivanja slova `"a"` u podstringu `s3`.

In [11]:
tekst = "  PyThOn 123 rastura!  "
tekst = tekst.strip()

i1 = tekst.find(" ")
i2 = tekst.find(" ", i1 + 1)

s1 = tekst[:i1]
print(s1)
s2 = tekst[i1 + 1:i2]
print(s2)
s3 = tekst[i2 + 1:]
print(s3)

print(s1.isalnum())
print(s2.isdigit())
print(s3.isalnum())

print(s1, "počinje s Pyt:", s1.startswith("PyT"))
print(s1, "završava s On:", s1.endswith("On"))
print(s3, "ima", s3.count("a"), "slova a")

PyThOn
123
rastura!
True
True
False
PyThOn počinje s Pyt: True
PyThOn završava s On: True
rastura! ima 2 slova a


#### Metode za zamjenu i manipulaciju sadržaja stringa

Python nudi metode koje omogućuju **promjenu, dijeljenje i spajanje stringova**. Ove metode su korisne kada želimo zamijeniti dijelove teksta, razdvojiti tekst u dijelove ili spojiti elemente u novi string.


**Najčešće korištene metode:**

| Metoda              | Opis                                                              | Primjer                     | Rezultat          |
| ------------------- | ----------------------------------------------------------------- | --------------------------- | ----------------- |
| `.replace(old,new)` | Zamjena dijela stringa                                            | `"Python".replace("P","J")` | `'Jython'`        |
| `.split(sep=None)`  | Razdvajanje stringa u listu po separatoru                         | `"a,b,c".split(",")`        | `['a','b','c']`   |
| `.join(iterable)`   | Spajanje elemenata liste u string                                 | `",".join(['a','b','c'])`   | `'a,b,c'`         |
| `.partition(sep)`   | Dijeli string na tri dijela: prije separatora, separator, poslije | `"a-b-c".partition("-")`    | `('a','-','b-c')` |
| `.rpartition(sep)`  | Isto kao partition, ali počinje s desne strane                    | `"a-b-c".rpartition("-")`   | `('a-b','-','c')` |

>  **Napomena**
>
> Ako u metodi `.split()` nije naveden argument `sep` onda će razdvojiti string po praznim znakovima (`" "`, `"\n"`, `"\t"`). 

✏️ **Zadatak:**

1. Definiraj varijablu `tekst` i dodijeli joj rečenicu s najmanje 15 znakova, npr. `"Python je zabavan i dobar!"`.
2. Zamijeni riječ `"zabavan"` s `"najzabavniji"`.
3. Zamijeni riječ `"dobar"` s `"najbolji"`.
4. Razdvoj tekst na listu riječi pomoću `.split()`.
5. Spoji listu riječi natrag u string koristeći `.join()`, s razmakom `"-"` između riječi.
6. Upotrijebi `.partition()` da izdvoji prvu riječ i ostatak stringa.
7. Upotrijebi `.rpartition()` da izdvoji zadnju riječ i ostatak stringa.
8. Ispiši sve rezultate nakon svake operacije.

In [12]:
tekst = "Python je zabavan i dobar!"

tekst = tekst.replace("zabavan", "najzabavniji")
print(tekst)

tekst = tekst.replace("dobar", "najbolji")
print(tekst)

rijeci = tekst.split()
print(rijeci)

novi_tekst = "-".join(rijeci)
print(novi_tekst)

print(tekst.partition("je"))
print(tekst.rpartition(" i "))


Python je najzabavniji i dobar!
Python je najzabavniji i najbolji!
['Python', 'je', 'najzabavniji', 'i', 'najbolji!']
Python-je-najzabavniji-i-najbolji!
('Python ', 'je', ' najzabavniji i najbolji!')
('Python je najzabavniji', ' i ', 'najbolji!')



---

#### Metoda za formatiranje stringa

Metoda `.format()` omogućuje **dinamičko umetanje vrijednosti** unutar stringa. Unutar stringa koristimo **vitičaste zagrade `{}`** koje se zamjenjuju vrijednostima koje proslijedimo metodi `.format()`.

>  **Napomena**  
> 
> * Originalni string ostaje nepromijenjen; metoda vraća **novi string** s umetnutim vrijednostima.

**Primjeri:**

```python
# Jedna vrijednost
recenica1 = "Pozdrav, {}!".format("Ana")
print(recenica1)  # Pozdrav, Ana!

# Više vrijednosti
a, b = 3, 4
recenica2 = "{} + {} = {}".format(a, b, a+b)
print(recenica2)  # 3 + 4 = 7

# Korištenje indeksa ili imena
recenica3 = "{1} + {0} = {2}".format(a, b, a+b)
print(recenica3)  # 4 + 3 = 7

recenica4 = "{ime} ima {godine} godina.".format(ime="Ana", godine=25)
print(recenica4)  # Ana ima 25 godina.
```

**Formatiranje brojeva**

`.format()` omogućava naprednu kontrolu nad brojevima: broj decimala, znanstvena notacija, postotci...

| Sintaksa  | Značenje                         | Primjer                                           |
| --------- | -------------------------------- | ------------------------------------------------- |
| `{:.2f}`  | realni broj s 2 decimale         | `"{:.2f}".format(3.14159)` → `"3.14"`             |
| `{:.3e}`  | znanstvena notacija s 3 decimale | `"{:.3e}".format(12345)` → `"1.235e+04"`          |
| `{:,.2f}` | dodaje tisućice i 2 decimale     | `"{:,.2f}".format(1234567.89)` → `"1,234,567.89"` |
| `{:.0%}`  | postotci bez decimala            | `"{:.0%}".format(0.876)` → `"88%"`                |

> 
> **Napomena za `round()`**  
> Kada koristimo `.2f`, rezultat se zaokružuje prema Pythonovom pravilu **round half to even** (bankarsko zaokruživanje), a ne klasičnom školskom.

**Formatiranje stringova**

Formatiranje omogućava da tekst bude centriran, lijevo ili desno poravnat, kao i dodavanje ispune (padding):

| Sintaksa  | Značenje                           | Primjer                                    |
| --------- | ---------------------------------- | ------------------------------------------ |
| `{:>10}`  | desno poravnanje u polju širine 10 | `"{:>10}".format("Ana")` → `"       Ana"`  |
| `{:^10}`  | centrirano poravnanje              | `"{:^10}".format("Ana")` → `"   Ana    "`  |
| `{:<10}`  | lijevo poravnanje                  | `"{:<10}".format("Ana")` → `"Ana       "`  |
| `{:*^10}` | centrirano s ispunom znakovima `*` | `"{:*^10}".format("Ana")` → `"***Ana****"` |

✏️ **Zadatak:**

1. Definiraj varijable: `ime = "Ana"`, `predmet = "Matematika"`, `prosjek = 4.355`, `bodovi = 98765.4321`.
2. Koristi `.format()` da ispišeš rečenicu: `Studentica ...Ana.... položila je predmet Matematika s prosjekom 4.36 (87%) i ima ukupno 98,765.43 bodova.`.
    * ime je centralno poravnato s ispunom znakovima `.`
    * predmet nema poravnanja ni ispune
    * prosjek je zaokružen na dvije decimale
    * prosjek podijeljen s `5` formatirai kao postotak bez decimala
    * bodove formatirati s tisućicama i 2 decimale


In [13]:
ime = "Ana"
predmet = "Matematika"
prosjek = 4.355
bodovi = 98765.4321

rezultat = "Učenica {:^10} položila je predmet {} s prosjekom {:.2f} (≈{:.0%}) i ostvarila {:,.2f} bodova.".format(
    ime, predmet, prosjek, prosjek/5, bodovi)

print(rezultat)

Učenica    Ana     položila je predmet Matematika s prosjekom 4.36 (≈87%) i ostvarila 98,765.43 bodova.


#### f-string

Od Pythona 3.6 uveden je novi, vrlo praktičan način za formatiranje stringova – **f-stringovi** (*formatted string literals*).
Pišu se tako da ispred stringa stavimo slovo `f`, a u vitičaste zagrade `{}` stavljamo varijable ili izraze.

**Primjeri:**

```python
ime = "Ana"
godine = 23
print(f"Moje ime je {ime} i imam {godine} godina.")  # Moje ime je Ana i imam 23 godina.

a, b = 5, 7
print(f"Zbroj {a} i {b} je {a + b}.")  # Zbroj 5 i 7 je 12.
```

>  **Napomena**  
> Unutar `{}` možemo koristiti iste **format specifikatore** kao kod `.format()`  
> na primjer, ako je `pi = 3.14159` onda `f"{pi:.2f}"` daje `"3.14"`.

✏️ **Zadatak:**

1. Definiraj varijable: `ime = "Ana"`, `predmet = "Matematika"`, `prosjek = 4.355`, `bodovi = 98765.4321`.
2. Koristi f-string da ispišeš rečenicu: `Studentica ...Ana.... položila je predmet Matematika s prosjekom 4.36 (87%) i ima ukupno 98,765.43 bodova.`.
    * ime je centralno poravnato s ispunom znakovima `.`
    * predmet nema poravnanja ni ispune
    * prosjek je zaokružen na dvije decimale
    * prosjek podijeljen s `5` formatirai kao postotak bez decimala
    * bodove formatirati s tisućicama i 2 decimale

In [14]:
ime = "Ana"
predmet = "Matematika"
prosjek = 4.355
bodovi = 98765.4321

rezultat = f"Učenica {ime:^10} položila je predmet {predmet} s prosjekom {prosjek:.2f} (≈{prosjek/5:.0%}) i ostvarila {bodovi:,.2f} bodova."

print(rezultat)

Učenica    Ana     položila je predmet Matematika s prosjekom 4.36 (≈87%) i ostvarila 98,765.43 bodova.


# 1. Varijable

## 1.3. Prikaz vrijednosti

U Pythonu postoje dva osnovna načina prikazivanja vrijednosti ostvarani funkcijama:

* `print()` - ispisuje podatke u čitljivom obliku za korisnika.
* `repr()` - vraća službeni tekstualni prikaz objekta, koristan za programere, debugiranje ili logiranje.

| Funkcija  | Svrha                                                          | Primjer                                   |
| --------- | -------------------------------------------------------------- | ----------------------------------------- |
| `print()` | Prikaz za korisnika, čitljivo                                  | `print("Ana\nAnić")` → ispisuje: <br> Ana |
| `repr()`  | Prikaz za programera, uključuje specijalne znakove i navodnike | `repr("Ana\nAnić")` → `'Ana\nAnić'`       |

>  **Napomena**  
> 
> * `repr()` je funkcija koja vraća string dok `print()` vraća `None` ali ispisuje podatke na izlaznoj jedinici (ekran). 


**Primjer**
```python
tekst = "Python\nJezik"

# Korisnički ispis
print(tekst)  
# Python
# Jezik

# Programerski prikaz
print(repr(tekst))  
# 'Python\nJezik'

# Direktno u f-string
print(f"Čitljivo: {tekst}")
print(f"Programerski: {tekst!r}")
```

✏️ **Zadatak:**

1. Definiraj varijablu:  
   ```
   s = "Ovo je 'tekst'\nSljedeći red"
   ```
2. Ispiši varijablu `s` pomoću `print()`.
3. Ispiši varijablu `s` pomoću `repr()`.
4. Kreiraj f-string koji istovremeno ispisuje čitljiv i programerski prikaz:
   `"Čitljivo: ..., Programerski: ..."`


In [15]:
s = "Ovo je 'tekst'\nSljedeći red"

# print
print(s)
# Ovo je 'tekst'
# Sljedeći red

# repr
print(repr(s))
# "Ovo je 'tekst'\nSljedeći red"

# f-string kombinacija
print(f"\nČitljivo: {s}\nProgramerski: {s!r}")
# Čitljivo: Ovo je 'tekst'
# Sljedeći red, Programerski: "Ovo je 'tekst'\nSljedeći red"


Ovo je 'tekst'
Sljedeći red
"Ovo je 'tekst'\nSljedeći red"

Čitljivo: Ovo je 'tekst'
Sljedeći red
Programerski: "Ovo je 'tekst'\nSljedeći red"


# 3. Kontrola tijeka

## 3.5. Bezuvjetna petlja: `for-else`

**for petlja** u Pythonu koristi se za iteriranje kroz sekvence, poput **listi, stringov-a** ili čak **range** funkcije.
Sintaksa je jednostavna: ispisujemo `for varijabla in sekvenca:`, a ispod uvučenim blokom pišemo naredbe koje će se izvršiti za svaki element.

**Primjeri:**

```python
# Iteriranje kroz string
ime = "Ana"
for slovo in ime:
    print(slovo)
```

✏️ **Zadatak:**

1. Iteriraj kroz string `"Python"` i ispiši indeks slova i samo slovo u novom retku.

In [16]:
i = 0
for slovo in "Python":
    print(i, slovo)
    i += 1

0 P
1 y
2 t
3 h
4 o
5 n


### 3.5.1. `for` petlja i `range()`

U Pythonu, **for petlja** omogućuje da **ponovimo neku radnju više puta**, a **`range()`** često se koristi za generiranje brojeva koje ćemo koristiti u petlji.
Na taj način možemo iterirati kroz niz brojeva.

**Sintaksa**

```python
for varijabla in range(start, stop, step):
    # tijelo petlje
```
* `start` – početna vrijednost (unaprijed zadana vrijednost je 0)
* `stop` – kraj niza (nije uključen)
* `step` – korak između dva broja (unaprijed zadana vrijednost je 1)

>  **Napomena**
>
> * `range()` prima **pozicijske argumente s zadanim vrijednostima**:
>
>   * Ako navedemo samo jedan argument, to je `stop`, dok `start=0` i `step=1`.
>   * Ako navedemo dva argumenta, to su `start` i `stop`, dok `step=1`.
>   * Ako navedemo tri argumenta, koristi se `start`, `stop` i `step`.
> * `range()` vraća **iterabilni objekt**, a ne listu. Za listu koristimo `list(range(...))`.

**Ispis brojeva od 0 do 4**

```python
for i in range(5):
    print(i)
```
**Ispis brojeva od 2 do 6**

```python
for i in range(2, 7):
    print(i)
```

**Ispis brojeva od 1 do 10 s korakom 2**

```python
for i in range(1, 11, 2):
    print(i)
```

**Odbrojavanje unatrag**

```python
for i in range(5, 0, -1):
    print(i)
```

✏️ **Zadatak:**

1. Ispiši sve brojeve od 0 do 30 koji su djeljivi s 3.
2. Izračunaj zbroj prvih 10 prirodnih brojeva.
3. Napravi odbrojavanje od 15 do 0 s korakom 3.
4. Definiraj varijablu `s="Python"`. Koristeći `range()` i `len()` ispiši pozicije i znakove stringa `s`.

In [1]:
for i in range(31):
    if i % 3 == 0:
        print(i)

print()

suma = 0
for i in range(1, 11):
    suma += i
print("Suma =", suma)

print()

for i in range(15, -1, -3):
    print(i)

print()

s = "Python"
for i in range(len(s)):
    print(i, s[i])


0
3
6
9
12
15
18
21
24
27
30

Suma = 55

15
12
9
6
3
0

0 P
1 y
2 t
3 h
4 o
5 n
